version: '3.9'

services:
  app:
    build: .
    depends_on:
      - "mongo"
    ports:
      - 3000:3000
    enviroment:
      MONGODB : mongodb://root:example@mongo:27017/ToDo-API
      KEY: xxxxxxxxxxxxxxxxx
  mongo:
    image: mongo
    restart: always
    volumes:
      - nodeApp:/home/node/app
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example 

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/

volumes:
  nodeApp: